"""add insight_embeddings table

Revision ID: 466adcdc6b9d
Revises: 13c68e8ec8da
Create Date: 2025-11-13 16:54:48.837448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466adcdc6b9d'
down_revision: Union[str, Sequence[str], None] = '13c68e8ec8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
