"""add NLP fields to insights

Revision ID: 9dfed2618c4d
Revises: 3c0b7208039a
Create Date: 2025-11-12 15:33:05.779275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfed2618c4d'
down_revision: Union[str, Sequence[str], None] = '3c0b7208039a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('sentiment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'sentiment')
    # ### end Alembic commands ###
