"""Add insight_embeddings table

Revision ID: b9dd4f5f39dc
Revises: 466adcdc6b9d
Create Date: 2025-11-15 17:15:44.706158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9dd4f5f39dc'
down_revision: Union[str, Sequence[str], None] = '466adcdc6b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insight_embeddings_cluster_id'), table_name='insight_embeddings')
    op.drop_index(op.f('ix_insight_embeddings_id'), table_name='insight_embeddings')
    op.drop_table('insight_embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('insight_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('insight_embeddings_insight_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_embeddings_pkey'))
    )
    op.create_index(op.f('ix_insight_embeddings_id'), 'insight_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_insight_embeddings_cluster_id'), 'insight_embeddings', ['cluster_id'], unique=False)
    # ### end Alembic commands ###
